services:
  - type: web
    name: citicare-api
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma migrate deploy
    startCommand: npx tsx src/server.ts
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: citicare-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: citicare-db
    plan: free
    databaseName: citicare
    region: singapore
